server:
  port: 8080

spring:
  application:
    name: gateway-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
gateway:
  message: "API Gateway - single config"
